version: "3.9"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Test123456
      MYSQL_DATABASE: betflix
      MYSQL_USER: admin
      MYSQL_PASSWORD: Test123456
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: Test123456
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
