version: "3.9"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Test123456
      MYSQL_DATABASE: betflix
      MYSQL_USER: admin
      MYSQL_PASSWORD: Test123456
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Test123456
    networks:
      - mynetwork

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: Test123456
      DB_NAME: betflix
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
